apiVersion: v1
kind: Pod

metadata:
  name: task-api-pod

spec:
  containers:
    - name: task-api

      image: dockerhub942/task-manager-api:latest

      ports:
        - containerPort: 8000

      env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@host.docker.internal:5432/task_manager"

        - name: SECRET_KEY
          value: "ThisIsOurSecretKeyForDevelopment"

        - name: ALGORITHM
          value: "HS256"

        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"

        - name: DEBUG
          value: "False"