apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: task-api-rs
  namespace: task-manager

spec:
  replicas: 1

  selector:
    matchLabels:
      app: task-api

  template:
    metadata:
      labels:
        app: task-api

    spec:
      containers:
      - name: task-api

        image: dockerhub942/task-manager-api:latest

        ports:
        - containerPort: 8000

        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/task_manager"

        - name: SECRET_KEY
          value: "ThisIsOurSecretKeyForDevelopment"

        - name: ALGORITHM
          value: "HS256"

        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"

        - name: DEBUG
          value: "False"