apiVersion: v1
kind: Secret

metadata:
  name: task-api-secret
  namespace: task-manager

type: Opaque

stringData:
  SECRET_KEY: ThisIsOurSecretKeyForDevelopment
  DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/task_manager